# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "53213a1e92ae4695646a8897fb5ffe70"
name = "Rainmaker AI"
application_url = "https://ai-rainmaker.gadget.app/api/shopify/install-or-render"
embedded = true

[auth]
redirect_urls = ["https://ai-rainmaker.gadget.app/api/connections/auth/shopify/callback"]

[webhooks]
api_version = "2025-10"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request", "customers/redact" ,"shop/redact"]
uri = "https://ai-rainmaker.gadget.app/api/webhooks/shopify"
